# Generated by Django 5.1.6 on 2025-03-03 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('tripId', models.AutoField(primary_key=True, serialize=False)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('num_days', models.IntegerField()),
                ('total_kilometer', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('dailylogID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_miles_driven', models.IntegerField()),
                ('total_mileage', models.IntegerField()),
                ('carrier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('office_address', models.TextField(blank=True, null=True)),
                ('vehicle_details', models.CharField(blank=True, max_length=100, null=True)),
                ('duty_status', models.JSONField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='trips.trip')),
            ],
        ),
    ]
