# Generated by Django 5.1.6 on 2025-03-03 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailylog',
            old_name='trip',
            new_name='tripId',
        ),
    ]
