# Generated by Django 5.1.6 on 2025-03-03 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_rename_trip_dailylog_tripid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailylog',
            old_name='dailylogID',
            new_name='dailylogId',
        ),
    ]
