# Generated by Django 5.1.6 on 2025-03-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_dailylog_duty_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='from_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='home_terminal_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='main_office_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='to_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
